### ISSUE TITLE
JDK 7 download KO 😭

### ISSUE THREAD

**Issue by fbiville** [jcgay/dotfiles#1]
https://github.com/jcgay/dotfiles/blob/23ee2804dea9ca1d75e1b8b3f6f1d92dad32eb5d/java/install.sh#L14

**Comment by jcgay** [comment]
Yes we need to login on the Oracle website to download a JDK 7 now :s
Even with the latest version: http://download.oracle.com/otn/java/jdk/7u80-b15/jdk-7u80-macosx-x64.dmg

I have switched to http://sdkman.io at work: https://github.com/jcgay/dotfiles/commit/4d6e0f67807b6d9a25073b178f72279355871995
